# -*- coding: utf-8 -*-
"""mALBERT_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3sjywKexiv6Y9H3c7lrpRlVGJ6Zv4bC

## Step 1: Set Up Environment.
"""

from google.colab import drive
drive.mount('/content/drive')

# Install required libraries (Run this only once in Colab)
!pip install transformers datasets torch scikit-learn pandas numpy tqdm

# Import necessary libraries
import torch  # PyTorch for deep learning
import pandas as pd  # Data manipulation and handling
import numpy as np  # Numerical operations
from sklearn.model_selection import train_test_split  # Splitting dataset into train/validation
from transformers import AlbertTokenizer, AlbertForSequenceClassification, Trainer, TrainingArguments  # Hugging Face model utilities
from datasets import Dataset, DatasetDict  # Hugging Face's dataset structure for easy data processing
from sklearn.metrics import accuracy_score, precision_recall_fscore_support  # Performance evaluation metrics
import random  # For setting random seeds
import os  # OS module to handle file paths and system-level operations

# Import AutoTokenizer from transformers
from transformers import AutoTokenizer

# Set a fixed random seed for reproducibility
SEED = 42  # Chosen arbitrarily for consistency
random.seed(SEED)  # Set seed for Python's random module
np.random.seed(SEED)  # Set seed for NumPy operations
torch.manual_seed(SEED)  # Set seed for PyTorch (CPU operations)
torch.cuda.manual_seed_all(SEED)  # Set seed for PyTorch (GPU operations, if available)

# Ensure deterministic behavior (helps with reproducibility)
torch.backends.cudnn.deterministic = True  # Forces PyTorch to use deterministic algorithms
torch.backends.cudnn.benchmark = False  # Disables auto-tuning to avoid variation in training speeds

"""## Step 2: Import Data"""

# Import pandas for data handling
import pandas as pd  # Import pandas for data handling
from google.colab import drive  # Import drive module to access Google Drive

# Mount Google Drive to access files
drive.mount('/content/drive')

# Define the path to the dataset
file_path = "/content/drive/MyDrive/Colab Notebooks/FigLang_2024/EN_train.csv"

# Load the dataset into a pandas DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the dataset to understand its structure
print("Sample Data:")
print(df.head())

# Display basic information about the dataset
print("\nDataset Information:")
print(df.info())

# Display summary statistics of numerical columns (if applicable)
print("\nSummary Statistics:")
print(df.describe())

# Display the distribution of labels (to check class balance)
print("\nLabel Distribution:")
print(df['label'].value_counts())

"""## Step 3: Data Preprocessing"""

import re

# Drop the 'Unnamed: 0' column (irrelevant index)
df = df.drop(columns=['Unnamed: 0'])

# Function to clean text data
def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'\s+', ' ', text)  # Remove extra spaces
    text = re.sub(r'\W+', ' ', text)  # Remove special characters
    text = text.strip()  # Remove leading/trailing spaces
    return text

# Apply text cleaning
df['text'] = df['text'].apply(clean_text)

# Analyze class distribution again
label_counts = df['label'].value_counts()
print("Updated Label Distribution:\n", label_counts)

"""### Step 4: Handle Class Imbalance Using Class Weights"""

import numpy as np
from sklearn.utils.class_weight import compute_class_weight
import torch

# Extract labels
labels = df['label'].values

# Compute class weights (convert classes to NumPy array)
class_weights = compute_class_weight(class_weight='balanced', classes=np.array([0, 1]), y=labels)

# Convert class weights to tensor (for PyTorch)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32)

# Print class weights
print("Class Weights:", class_weights_tensor)

"""## Step 5: Tokenization"""

# Load mALBERT tokenizer
tokenizer = AutoTokenizer.from_pretrained("albert-base-v2")

# Define a function to tokenize the text data
def tokenize_data(examples):
    return tokenizer(
        examples["text"],  # Text column
        padding="max_length",  # Pad to max token length
        truncation=True,  # Truncate longer sequences
        max_length=512,  # Max token length for mALBERT
        return_tensors="pt"  # Convert to PyTorch tensors
    )

# Apply tokenization to the dataset
tokenized_data = df["text"].apply(lambda x: tokenize_data({"text": x}))

# Extract input_ids and attention masks
df["input_ids"] = tokenized_data.apply(lambda x: x["input_ids"].squeeze().tolist())
df["attention_mask"] = tokenized_data.apply(lambda x: x["attention_mask"].squeeze().tolist())

# Display a sample
print("Tokenized Sample:")
print(df[["text", "input_ids", "attention_mask"]].head())

"""## Step 6: Prepare Dataset for Training"""

from sklearn.model_selection import train_test_split
from datasets import Dataset

# Step 1: Split the data into training and validation sets
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['text'], df['label'], test_size=0.2, stratify=df['label'], random_state=42
)

# Step 2: Tokenize the training and validation texts
train_encodings = tokenizer(train_texts.tolist(), truncation=True, padding=True, max_length=512)
val_encodings = tokenizer(val_texts.tolist(), truncation=True, padding=True, max_length=512)

# Step 3: Convert the tokenized texts and labels into Huggingface's Dataset format
train_dataset = Dataset.from_dict({
    'input_ids': train_encodings['input_ids'],
    'attention_mask': train_encodings['attention_mask'],
    'labels': train_labels.tolist()
})

val_dataset = Dataset.from_dict({
    'input_ids': val_encodings['input_ids'],
    'attention_mask': val_encodings['attention_mask'],
    'labels': val_labels.tolist()
})

# Step 4: Check the dataset formats
print("Train Dataset Format:", train_dataset)
print("Validation Dataset Format:", val_dataset)

"""## Step 7: Load the Model"""

# Load the pre-trained mALBERT model for sequence classification
model = AlbertForSequenceClassification.from_pretrained('albert-base-v2', num_labels=2)

# Check the model architecture
print(model)

"""## Step 8: Define Training Arguments"""

# Step 8: Define Training Arguments with modified hyperparameters
from transformers import TrainingArguments

# Modify the training arguments to optimize model performance
training_args = TrainingArguments(
    output_dir="./results",  # Directory to save model checkpoints
    num_train_epochs=10,  # Increased number of epochs to allow more training time (was 5)
    per_device_train_batch_size=16,  # Increase batch size for better performance (was 8)
    per_device_eval_batch_size=16,  # Increased evaluation batch size (was 8)
    warmup_steps=500,  # Number of warmup steps (helps with stable training)
    weight_decay=0.01,  # Regularization to prevent overfitting
    logging_dir="./logs",  # Directory for storing logs
    logging_steps=100,  # Log metrics every 100 steps
    eval_strategy="epoch",  # Evaluate at the end of each epoch
    save_strategy="epoch",  # Save the model at the end of each epoch
    load_best_model_at_end=True,  # Load the best model (based on validation loss)
    metric_for_best_model="eval_loss",  # Choose the best model based on validation loss
    greater_is_better=False,  # Lower validation loss is better
    learning_rate=2e-5,  # Slightly lower learning rate for better convergence
    adam_epsilon=1e-8,  # Set epsilon value for the Adam optimizer to avoid numerical issues
)

print("Training arguments successfully defined!")

"""## Step 9: Train the Model"""

# Step 9: Train the Model
from transformers import Trainer

# Define the Trainer
trainer = Trainer(
    model=model,  # The XLM-Roberta model
    args=training_args,  # Updated training arguments
    train_dataset=train_dataset,  # Training dataset
    eval_dataset=val_dataset,  # Validation dataset
    compute_metrics=None,  # No need for custom metrics, as you're only tracking validation loss
    # tokenizer=tokenizer,  # Removed as it's not a valid argument for Trainer
)

# Train the model
trainer.train()

print("Training completed successfully!")

"""## Step 10: Evaluate the Model"""

# Step 10: Evaluate the Model
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Define the evaluation function
def evaluate_model(trainer, eval_dataset):
    # Make predictions using the trained model
    predictions, labels, _ = trainer.predict(eval_dataset)

    # Convert logits to predicted classes
    preds = np.argmax(predictions, axis=-1)

    # Generate the classification report
    report = classification_report(labels, preds, target_names=["0", "1"])

    # Print validation accuracy and classification report
    accuracy = np.mean(labels == preds)
    print(f"Validation Accuracy: {accuracy:.4f}\n")
    print("Classification Report:")
    print(report)

    # Generate confusion matrix
    cm = confusion_matrix(labels, preds)

    # Plot confusion matrix
    plt.figure(figsize=(6, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=["0", "1"], yticklabels=["0", "1"])
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.show()

# Evaluate the model on the validation set
evaluate_model(trainer, val_dataset)

"""## Step 11: Test the Model."""

import pandas as pd

# Load the test dataset
test_file_path = "/content/drive/MyDrive/Colab Notebooks/FigLang_2024/EN_test.csv"
test_df = pd.read_csv(test_file_path)

# Preview the test dataset (optional)
print("Test Data Sample:")
print(test_df.head())

# Preprocess the text in the test dataset (use the same tokenizer as before)
test_encodings = tokenizer(test_df['text'].tolist(), truncation=True, padding=True, max_length=512)

# Create a PyTorch dataset for the test set
class TestDataset(torch.utils.data.Dataset):
    def __init__(self, encodings):
        self.encodings = encodings

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        return item

    def __len__(self):
        return len(self.encodings['input_ids'])

test_dataset = TestDataset(test_encodings)

# Make predictions on the test set
predictions, _, _ = trainer.predict(test_dataset)

# Convert logits to predicted labels (0 or 1)
test_preds = predictions.argmax(axis=-1)

# Create a new DataFrame with the test data and predicted labels
output_df = test_df[['Unnamed: 0', 'text']].copy()  # Use the correct column name for 'index'
output_df['predicted_label'] = test_preds

# Save the predictions to a new CSV file
output_file_path = "/content/drive/MyDrive/Colab Notebooks/mALBERT/test_predictionbyMALBERT.csv"
output_df.to_csv(output_file_path, index=False)

# Inform the user
print(f"Test predictions saved successfully at {output_file_path}")

import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

# Load the reference (true) labels from the test reference file
reference_file_path = "/content/drive/MyDrive/Colab Notebooks/FigLang_2024/EN_reference_test.csv"
reference_df = pd.read_csv(reference_file_path)

# Load the predicted labels from the previous output file
predicted_df = pd.read_csv(output_file_path)

# Ensure that the order of rows matches (if necessary)
reference_labels = reference_df['label']
predicted_labels = predicted_df['predicted_label']

# Calculate the test accuracy
test_accuracy = accuracy_score(reference_labels, predicted_labels)
print(f"Test Accuracy: {test_accuracy:.4f}")

# Calculate the classification report
class_report = classification_report(reference_labels, predicted_labels)

# Print classification report
print("Classification Report:")
print(class_report)

# Generate the confusion matrix
conf_matrix = confusion_matrix(reference_labels, predicted_labels)

# Plot confusion matrix using seaborn
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Non-Euphemism", "Euphemism"],
            yticklabels=["Non-Euphemism", "Euphemism"])
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Generate the confusion matrix
conf_matrix = confusion_matrix(reference_labels, predicted_labels)

# Plot confusion matrix using seaborn
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues", xticklabels=["Non-Euphemism", "Euphemism"], yticklabels=["Non-Euphemism", "Euphemism"])
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

"""## Step 12: Save the model"""

# Step 13: Save the model
model_save_path = "/content/drive/MyDrive/Colab Notebooks/mALBERT/mALBERTModel"
# Save the model and tokenizer
model.save_pretrained(model_save_path)
tokenizer.save_pretrained(model_save_path)

print(f"Model and tokenizer saved successfully at: {model_save_path}")

"""## Step 13: Taking Input and  Generate Output

"""